# baseURL: /preview/
baseURL: /
languageCode: en-us
title: ClodPi Labs
theme: hugo-fresh
publishDir: docs


params:
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: IoT & ClodPi
    # Hero subtitle (optional)
    subtitle: We build products in Low Power Long Range sensor data network communication space, using technologies like LoRaWAN and NB-IoT
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "https://console.clodpi.io/docs/getting-started"
    # Hero image (from /images/___)
    image: illustrations/lora.png
    # Footer logos (from /images/logos/clients/___.svg)
  hero1:
    title: We got you covered!
    subtitle: We are expanding our LoRaWAN network coverage across India. Express your interest to get your prefered location covered with our network. It is open and free for development.
    buttontext: Submit Now
    buttonlink: "https://goo.gl/forms/6IT822kZ4mk5HlhV2"
    image: illustrations/coverage.png
  meta:
    keywords: ClodPi, LoRa, LoRaWAN, Gateway, Network Server, India, Indoor, Outdoor, IoT, Automation, Dashboard, Research, Development, Services, Hardware, Software, Platform
    description: ClodPi's products ranges from LoRaWAN Gateways (Indoor & Outdoor), Network Servers alongn with Dasboards and Nodes helps in Long Range Low Power IoT Communication. We also work on cutting edge technologies like NBIoT, Edge Computing, etc
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Products
    url: /#products
  - title: Pricing
    url: /#pricing
  - title: Solutions
    sublinks:
    - title: Wireless Energy Metering
      url: /#products
    - title: Modbus Wireless Reader
      url: /#products
    - title: Smart Street Lights
      url: /#products
    - title: Monitoring Dashboards
      url: /#screenshot
  - title: LoRaWAN Console
    url: https://console.clodpi.io
    button: true
  section1:
    title: Our LoRaWAN Products
    tiles:
    - title: Industrial Outdoor Gateway
      icon: outdoor-gw
      text: Outdoor (IP68) LoRaWAN 8 channel gateway with 4g backhaul and Power over Ethernet.
      url: https://shop.clodpi.io/products/lorawan-outdoor-gateway
      buttonText: More Details
    - title: Indoor Gateway
      icon: indoor-gw
      text: Indoor, 8 channel gateway with ethernet backhaul, speicifcally for covering industries and comercial buildings.
      url: https://shop.clodpi.io/products/lorawan-indoor-industrial
      buttonText: More Details
    - title: Hosted (SaaS) Network Server
      icon: console
      text: Network server (LoRaWAN v1.0.1) to bridge the gateways to your application, doing device management and decode / relay the data from nodes in a secure manner.
      url: https://console.clodpi.io
      buttonText: Get started
    - title: LoRaWAN Development Kit
      icon: dev-kit
      text: Includes nodes, one indoor LoRaWAN gateway, and subscription to the network server.
    - title: LoRaWAN RS485 Adapter
      icon: rs485
      text: Enables LoRaWAN connectivity to existing rs485/modbus based energy, water, gas meters and other industrial equipments.
    - title: LoRaWAN Parking Sensor
      icon: parking
      text: LoRaWAN parking sensors for commercial and public parking spaces.
    - title: LoRaWAN Street Lights
      icon: light
      text: Control, monitor and measure energy consumption of street lights with LoRaWAN. Supports other features auto dimming, motion based triggers, etc.
    - title: LoRaWAN multi-sensors node
      icon: multisensor
      text: Generic LoRaWAN multi-sensors node to quickly develop your applications and prototypes
  section2:
    title: You're here because you want the best
    subtitle: And we know it
    features:
    - title: Powerful and unified interface
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: Cross-device synchronisation
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: doc-sync
    - title: Nomad system
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: mobile-feed
  screenshot:
    title: Dashboard
    subtitle: for monitoring
    image: illustrations/mockups/app-mockup.png
  pricing:
    buttonText: Contact Us
    buttonLink: "mailto:meetus@clodpi.io"
  footer:
    # Logo (from /images/logos/___)
    logo: logos/logo-white.png
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/clodpi
      # Icons are from Font Awesome
      icon: github
    - link: https://www.facebook.com/clodpilabs/
      icon: facebook
    - link: https://twitter.com/clodpilabs
      icon: twitter
    bulmalogo: true
    product:
    - text: About LoRaWAN
      link: https://lora-alliance.org/about-lorawan
    - text: LoRaWAN in India
      link: /
    docs:
    - text: Get started
      link: https://console.clodpi.io/docs/getting-started
    - text: User guides
      link: https://console.clodpi.io/docs/getting-started
