# baseURL: /preview/
baseURL: /
languageCode: en-us
title: ClodPi Labs
theme: hugo-fresh
publishDir: docs


params:
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: IoT & ClodPi
    # Hero subtitle (optional)
    subtitle: We build products in Low Power Long Range sensor data network communication space, using technologies like LoRaWAN® and NB-IoT
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "https://console.clodpi.io/docs/getting-started"
    # Hero image (from /images/___)
    image: illustrations/lora.png
    # Footer logos (from /images/logos/clients/___.svg)
  hero1:
    title: We got you covered!
    subtitle: We are expanding our LoRa network coverage across India. Express your interest to get your prefered location covered with our network. It is open and free for development.
    buttontext: Submit Now
    buttonlink: "https://goo.gl/forms/6IT822kZ4mk5HlhV2"
    image: illustrations/coverage.png
  meta:
    keywords: ClodPi, LoRa, LoRaWAN, Gateway, Network Server, India, Indoor, Outdoor, IoT, Automation, Dashboard, Research, Development, Services, Hardware, Software, Platform
    description: ClodPi's products ranges from LoRaWAN Gateways (Indoor & Outdoor), Network Servers alongn with Dasboards and Nodes helps in Long Range Low Power IoT Communication. We also work on cutting edge technologies like NBIoT, Edge Computing, etc
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Products
    url: /#products
  - title: Pricing
    url: /#pricing
  - title: Solutions
    sublinks:
    - title: Wireless Energy Metering
      url: /#products
    - title: Modbus Wireless Reader
      url: /#products
    - title: Smart Street Lights
      url: /#products
    - title: Monitoring Dashboards
      url: /#screenshot
  - title: Clodpi Console
    url: https://console.clodpi.io
    button: true
  section1:
    title: Our Products
    tiles:
    - title: Industrial Outdoor Gateway
      icon: outdoor-gw
      text: Outdoor (IP68) 8 channel gateway for LoRaWAN networks with 4g backhaul and Power over Ethernet.
      url: '#'
      buttonText: More Details
    - title: Indoor Gateway
      icon: indoor-gw
      text: Indoor, 8 channel gateway for LoRaWAN networks with ethernet backhaul, speicifcally for covering industries and comercial buildings.
      url: '#'
      buttonText: More Details
    - title: Hosted (SaaS) Network Server
      icon: console
      text: Network server for LoRaWAN to bridge the gateways to your application, doing device management and decode / relay the data from nodes in a secure manner.
      url: https://console.clodpi.io
      buttonText: Get started
    - title: Development Kit
      icon: dev-kit
      text: Get started with your development activities using LoRa technology. Includes radio modules (nodes), one indoor clodpi gateway, and subscription to the network server.
    - title: RS485 Adapter
      icon: rs485
      text: Enables LoRaWAN connectivity to existing rs485/modbus based energy, water, gas meters and other industrial equipments.
    - title: Parking Sensor
      icon: parking
      text: Parking sensors for commercial and public parking spaces, using LoRa technology
    - title: Street Lights
      icon: light
      text: Control, monitor and measure energy consumption of street lights with LoRaWAN network. Supports other features auto dimming, motion based triggers, etc.
    - title: General Purpose Button
      icon: button
      text: button to perform any action, based on LoRa technology. Control a light, start/stop an engine, etc. Its battery powered and maintenance free.
    - title: LoRa GPS Tracker
      icon: gps
      text: Track valuable assets location in realtime. USB or battery powered, with recharchable LiPo battery.
    - title: LoRa multi-sensors node
      icon: multisensor
      text: LoRa module with multi-sensors node to quickly develop your applications and prototypes
  screenshot:
    title: Dashboard
    subtitle: for monitoring
    image: illustrations/mockups/app-mockup.png
  pricing:
    buttonText: Contact Us
    buttonLink: "mailto:meetus@clodpi.io"
  footer:
    # Logo (from /images/logos/___)
    logo: logos/logo-white.png
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/clodpi
      # Icons are from Font Awesome
      icon: github
    - link: https://www.facebook.com/clodpilabs/
      icon: facebook
    - link: https://twitter.com/clodpilabs
      icon: twitter
    bulmalogo: true
    product:
    - text: About LoRaWAN
      link: https://lora-alliance.org/about-lorawan
    - text: LoRaWAN in India
      link: /
    docs:
    - text: Get started
      link: https://console.clodpi.io/docs/getting-started
    - text: User guides
      link: https://console.clodpi.io/docs/getting-started
